# Attestify Test Framework - Open Source

[package]
name = "test_framework_oss"
version = "0.2.5"
edition = "2024"

[features]
# keep assertions available by default, nape_filesystem opt-in
default = ["assertions"]
assertions = []
nape_filesystem = []

[dev-dependencies]
kernel_oss = { git = "https://github.com/attestify/kernel-oss.git", tag = "0.4.0", version = "=0.4.0" }
